paths:
  /bookings/{id}/review:
    patch:
      tags:
        - Bookings
      summary: Review booking
      operationId: reviewBooking
      parameters:
        - name: id
          in: path
          description: Booking ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewBookingPayload'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - Bearer: []
  /bookings/{id}/pet:
    patch:
      tags:
        - Bookings
      summary: Update booking pet
      operationId: updateBookingPet
      parameters:
        - name: id
          in: path
          description: Booking ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePetPayload'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - Bearer: []
  /bookings/{id}/status:
    patch:
      tags:
        - Bookings
      summary: Update booking status
      operationId: updateBookingStatus
      parameters:
        - name: id
          in: path
          description: Booking ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBookingStatusPayload'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - Bearer: []
  /bookings/{id}:
    get:
      tags:
        - Bookings
      summary: Find booking by Id
      operationId: findBookingById
      parameters:
        - name: id
          in: path
          description: Booking ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - Bearer: []
    patch:
      tags:
        - Bookings
      summary: Update booking
      operationId: updateBooking
      parameters:
        - name: id
          in: path
          description: Booking ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBookingPayload'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - Bearer: []
  /bookings:
    get:
      tags:
        - Bookings
      summary: Find bookings
      operationId: findBookings
      parameters:
        - name: search
          in: query
          description: Search value
          required: false
          schema:
            type: string
        - name: branch
          in: query
          description: Location filter
          required: false
          schema:
            type: string
        - name: service
          in: query
          description: Service filters
          required: false
          schema:
            type: string
        - name: status
          in: query
          description: Status filters
          required: false
          schema:
            type: string
        - name: pageNumber
          in: query
          description: Page number
          required: false
          schema:
            type: number
            default: 20
        - name: pageSize
          in: query
          description: Page size
          required: false
          schema:
            type: number
            default: 1
        - name: sortBy
          in: query
          description: Sort field
          required: false
          schema:
            type: string
            default: createdAt_desc
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindBookingsResult'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - Bearer: []
    post:
      tags:
        - Bookings
      summary: Create booking
      operationId: createBooking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookingPayload'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - Bearer: []
components:
  schemas:
    ReviewBookingPayload:
      type: object
      properties:
        rating:
          type: number
        review:
          type: string
    UpdateBookingStatusPayload:
      type: object
      properties:
        status:
          type: string
    FindBookingsResult:
      type: object
      properties:
        total:
          type: number
        data:
          type: array
          items:
            $ref: '#/components/schemas/Booking'
    CreateBookingServicePayload:
      type: object
      properties:
        service:
          type: string
        roomOption:
          type: string
        roomType:
          type: string
        extraCares:
          type: array
          items:
            type: string
        checkInTime:
          type: string
        checkOutTime:
          type: string
        lateCheckoutFee:
          type: number
    UpdateBookingPayload:
      type: object
      properties:
        pet:
          type: string
        pickupOption:
          type: string
        note:
          type: string
        services:
          type: array
          items:
            $ref: '#/components/schemas/CreateBookingServicePayload'
        branch:
          type: string
        additionalFees:
          type: array
          items:
            $ref: '#/components/schemas/BookingAddionalFee'
        checkoutNote:
          type: string
    CreateBookingPayload:
      type: object
      properties:
        pet:
          type: string
        pickupOption:
          type: string
        note:
          type: string
        services:
          type: array
          items:
            $ref: '#/components/schemas/CreateBookingServicePayload'
        branch:
          type: string
    BookingExtraCare:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        priceType:
          type: string
        price:
          type: number
        priceConfigs:
          type: array
          items:
            $ref: '#/components/schemas/PriceConfig'
        quantity:
          type: number
        quantityPerDay:
          type: number
        unit:
          type: string
    BookingService:
      type: object
      properties:
        _id:
          type: string
        service:
          $ref: '#/components/schemas/Service'
        roomOption:
          $ref: '#/components/schemas/RoomOption'
        roomType:
          $ref: '#/components/schemas/RoomType'
        extraCares:
          type: array
          items:
            $ref: '#/components/schemas/BookingExtraCare'
        checkInTime:
          type: string
        checkOutTime:
          type: string
        lateCheckoutFee:
          type: number
        quantity:
          type: number
        price:
          type: number
    BookingAddionalFee:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        price:
          type: number
    Booking:
      type: object
      properties:
        _id:
          type: string
        pet:
          $ref: '#/components/schemas/Pet'
        petOwner:
          $ref: '#/components/schemas/User'
        pickupOption:
          type: string
          enum: [CAR, BIKE, NONE]
        services:
          type: array
          items:
            $ref: '#/components/schemas/BookingService'
        note:
          type: string
        totalPrice:
          type: number
        branch:
          $ref: '#/components/schemas/Branch'
        status:
          type: string
          enum: [PENDING, UPCOMMING, IN_PROGRESS, FINISHED, CANCELLED]
        additionalFees:
          type: array
          items:
            $ref: '#/components/schemas/BookingAddionalFee'
        checkoutNote:
          type: string
        rating:
          type: number
        review:
          type: string
        createdAt:
          type: number
        createdBy:
          type: string
        lastModifiedAt:
          type: number
        lastModifiedBy:
          type: string
