paths:
  /services/find-all:
    get:
      tags:
        - Services
      summary: Find all services
      operationId: findAllServices
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindServicesResult'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - Bearer: []
components:
  schemas:
    PriceConfig:
      type: object
      properties:
        _id:
          type: string
        price:
          type: number
        minWeight:
          type: number
        maxWeight:
          type: number
    ExtraCare:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        priceType:
          type: string
        price:
          type: number
        priceConfigs:
          type: array
          items:
            $ref: '#/components/schemas/PriceConfig'
        quantityPerDay:
          type: number
        unit:
          type: string
    RoomType:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        price:
          type: number
        minWeight:
          type: number
        maxWeight:
          type: number
    Description:
      type: object
      properties:
        en:
          type: string
        vi:
          type: string
    RoomOption:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        shortDescription:
          $ref: '#/components/schemas/Description'
        description:
          $ref: '#/components/schemas/Description'
        roomTypes:
          type: array
          items:
            $ref: '#/components/schemas/RoomType'
        extraCares:
          type: array
          items:
            $ref: '#/components/schemas/ExtraCare'
    Service:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        shortDescription:
          $ref: '#/components/schemas/Description'
        description:
          $ref: '#/components/schemas/Description'
        roomOptions:
          type: array
          items:
            $ref: '#/components/schemas/RoomOption'
        priceType:
          type: string
          enum: [FIXED, BASE_ON_WEIGHT]
        price:
          type: number
        priceConfigs:
          type: array
          items:
            $ref: '#/components/schemas/PriceConfig'
        extraCares:
          type: array
          items:
            $ref: '#/components/schemas/ExtraCare'
        isActive:
          type: boolean
        createdAt:
          type: number
        createdBy:
          type: string
        lastModifiedAt:
          type: number
        lastModifiedBy:
          type: string
    FindServicesResult:
      type: object
      properties:
        total:
          type: number
        data:
          type: array
          items:
            $ref: '#/components/schemas/Service'
