export const permissionScopes = {
  OWN: 'OWN',
  ANY: 'ANY',
};

export const permissions = {
  USERS: {
    CREATE: 'USERS.CREATE',
    VIEW: 'USERS.VIEW',
    UPDATE: 'USERS.UPDATE',
    DELETE: 'USERS.DELETE',
  },
  ROLES: {
    CREATE: 'ROLES.CREATE',
    VIEW: 'ROLES.VIEW',
    UPDATE: 'ROLES.UPDATE',
    DELETE: 'ROLES.DELETE',
  },
  BREEDS: {
    CREATE: 'BREEDS.CREATE',
    VIEW: 'BREEDS.VIEW',
    UPDATE: 'BREEDS.UPDATE',
    DELETE: 'BREEDS.DELETE',
  },
  PETS: {
    CREATE: 'PETS.CREATE',
    VIEW: 'PETS.VIEW',
    UPDATE: 'PETS.UPDATE',
    DELETE: 'PETS.DELETE',
  },
  BRANCHES: {
    CREATE: 'BRANCHES.CREATE',
    VIEW: 'BRANCHES.VIEW',
    UPDATE: 'BRANCHES.UPDATE',
    DELETE: 'BRANCHES.DELETE',
  },
  SERVICES: {
    CREATE: 'SERVICES.CREATE',
    VIEW: 'SERVICES.VIEW',
    UPDATE: 'SERVICES.UPDATE',
    DELETE: 'SERVICES.DELETE',
  },
  BOOKINGS: {
    CREATE: 'BOOKINGS.CREATE',
    VIEW: 'BOOKINGS.VIEW',
    UPDATE: 'BOOKINGS.UPDATE',
    DELETE: 'BOOKINGS.DELETE',
  },
  NOTIFICATIONS: {
    CREATE: 'NOTIFICATIONS.CREATE',
    VIEW: 'NOTIFICATIONS.VIEW',
    UPDATE: 'NOTIFICATIONS.UPDATE',
    DELETE: 'NOTIFICATIONS.DELETE',
  },
};
