paths:
  /notifications/{id}/read:
    patch:
      tags:
        - Notifications
      summary: Read notification
      operationId: readNotification
      parameters:
        - name: id
          in: path
          description: Notification ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - Bearer: []
  /notifications:
    get:
      tags:
        - Notifications
      summary: Find notifications
      operationId: findNotifications
      parameters:
        - name: pageNumber
          in: query
          description: Page number
          required: false
          schema:
            type: number
            default: 20
        - name: pageSize
          in: query
          description: Page size
          required: false
          schema:
            type: number
            default: 1
        - name: sortBy
          in: query
          description: Sort field
          required: false
          schema:
            type: string
            default: createdAt_desc
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindNotificationsResult'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - Bearer: []
components:
  schemas:
    Notification:
      type: object
      properties:
        _id:
          type: string
        type:
          type: string
          enum: [CHECK_IN, CHECK_OUT, BOOKING_CONFIRM, BOOKING_SERVICE_UPDATE, BOOKING_FINISHED]
        booking:
          $ref: '#/components/schemas/Booking'
        read:
          type: boolean
        user:
          type: string
        createdAt:
          type: number
        createdBy:
          type: string
        lastModifiedAt:
          type: number
        lastModifiedBy:
          type: string
    FindNotificationsResult:
      type: object
      properties:
        total:
          type: number
        data:
          type: array
          items:
            $ref: '#/components/schemas/Notification'
